services:
  server:
    build: ./server
    container_name: avito-server
    ports:
      - "3000:3000"

  client:
    build: ./client
    container_name: avito-client
    ports:
      - "5173:5173"
    depends_on:
      - server
